workspace:
  base: /go
  path: src/

pipeline:

  pull-from-ecr:
    image: lpf190/drone-pull-ecr:v0.05
    access_id: ${ecr_access_key}
    secret_key: ${ecr_secret_key}
    region: ap-northeast-1
    commands:
      - docker pull 376045331903.dkr.ecr.ap-northeast-1.amazonaws.com/nginx:alpine-1.15.2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      event: push

  publish-base-image:
    image: plugins/ecr
    repo: 376045331903.dkr.ecr.ap-northeast-1.amazonaws.com/base-images/php-fpm-laravel
    registry: 376045331903.dkr.ecr.ap-northeast-1.amazonaws.com
    secrets: [ ecr_access_key, ecr_secret_key ]
    region: ap-northeast-1
    dockerfile: dockerfile-php-fpm-laravel
    tags:
      - latest
    when:
      branch: master
      event: push
