workspace:
  base: /go
  path: src/

pipeline:

  publish-base-image:
    image: plugins/ecr
    repo: 376045331903.dkr.ecr.ap-northeast-1.amazonaws.com/base-images/php-fpm-laravel
    registry: 376045331903.dkr.ecr.ap-northeast-1.amazonaws.com
    secrets: [ ecr_access_key, ecr_secret_key ]
    region: ap-northeast-1
    dockerfile: dockerfile-php-fpm-laravel
    tags:
      - latest
    when:
      branch: master
      event: push
